using System;

namespace Taco.Classes
{
    partial class TacoConfig
    {
        private static ConfigVer3 UpgradeV2ToV3(ConfigVer2 configVer2)
        {
            ConfigVer3 configVer3 = new ConfigVer3
            {
                PreserveWindowPosition = configVer2.PreserveWindowPosition,
                PreserveWindowSize = configVer2.PreserveWindowSize,
                WindowPositionX = configVer2.WindowPositionX,
                WindowPositionY = configVer2.WindowPositionY,
                WindowSizeX = configVer2.WindowSizeX,
                WindowSizeY = configVer2.WindowSizeY,
                PreserveFullScreenStatus = configVer2.PreserveFullScreenStatus,
                IsFullScreen = configVer2.IsFullScreen,
                PreserveHomeSystem = configVer2.PreserveHomeSystem,
                HomeSystemId = configVer2.HomeSystemId,
                MonitorBranch = configVer2.MonitorBranch,
                MonitorDeklein = configVer2.MonitorDeklein,
                MonitorTenal = configVer2.MonitorTenal,
                MonitorVenal = configVer2.MonitorVenal,
                MonitorFade = configVer2.MonitorFade,
                MonitorPureBlind = configVer2.MonitorPureBlind,
                MonitorTribute = configVer2.MonitorTribute,
                MonitorVale = configVer2.MonitorVale,
                MonitorProvidence = configVer2.MonitorProvidence,
                MonitorDelve = configVer2.MonitorDelve,
                MonitorGameLog = configVer2.MonitorGameLog,
                AlertBranch = configVer2.AlertBranch,
                AlertDeklein = configVer2.AlertDeklein,
                AlertTenal = configVer2.AlertTenal,
                AlertVenal = configVer2.AlertVenal,
                AlertFade = configVer2.AlertFade,
                AlertPureBlind = configVer2.AlertPureBlind,
                AlertTribute = configVer2.AlertTribute,
                AlertVale = configVer2.AlertVale,
                AlertProvidence = configVer2.AlertProvidence,
                AlertDelve = configVer2.AlertDelve,
                PreserveCameraDistance = configVer2.PreserveCameraDistance,
                PreserveLookAt = configVer2.PreserveLookAt,
                CameraDistance = configVer2.CameraDistance,
                LookAtX = configVer2.LookAtX,
                LookAtY = configVer2.LookAtY,
                OverrideLogPath = configVer2.OverrideLogPath,
                LogPath = configVer2.LogPath,
                PreserveSelectedSystems = configVer2.PreserveSelectedSystems,
                SelectedSystems = configVer2.SelectedSystems,
                DisplayNewFileAlerts = configVer2.DisplayNewFileAlerts,
                DisplayOpenFileAlerts = configVer2.DisplayOpenFileAlerts,
                AlertTriggers = configVer2.AlertTriggers,
                IgnoreStrings = configVer2.IgnoreStrings,
                IgnoreSystems = configVer2.IgnoreSystems,
                CharacterList = configVer2.CharacterList,
                DisplayCharacterNames = true,
                ShowCharacterLocations = true,
                CameraFollowCharacter = false,
                CentreOnCharacter = -1,
                MapRangeFrom = 0
            };
            return configVer3;
        }

        private static ConfigVer4 UpgradeV3ToV4(ConfigVer3 configVer3)
        {
            ConfigVer4 configVer4 = new ConfigVer4
            {
                PreserveWindowPosition = configVer3.PreserveWindowPosition,
                PreserveWindowSize = configVer3.PreserveWindowSize,
                WindowPositionX = configVer3.WindowPositionX,
                WindowPositionY = configVer3.WindowPositionY,
                WindowSizeX = configVer3.WindowSizeX,
                WindowSizeY = configVer3.WindowSizeY,
                PreserveFullScreenStatus = configVer3.PreserveFullScreenStatus,
                IsFullScreen = configVer3.IsFullScreen,
                PreserveHomeSystem = configVer3.PreserveHomeSystem,
                HomeSystemId = configVer3.HomeSystemId,
                MonitorBranch = configVer3.MonitorBranch,
                MonitorDeklein = configVer3.MonitorDeklein,
                MonitorTenal = configVer3.MonitorTenal,
                MonitorVenal = configVer3.MonitorVenal,
                MonitorFade = configVer3.MonitorFade,
                MonitorPureBlind = configVer3.MonitorPureBlind,
                MonitorTribute = configVer3.MonitorTribute,
                MonitorVale = configVer3.MonitorVale,
                MonitorProvidence = configVer3.MonitorProvidence,
                MonitorDelve = configVer3.MonitorDelve,
                MonitorGameLog = configVer3.MonitorGameLog,
                AlertBranch = configVer3.AlertBranch,
                AlertDeklein = configVer3.AlertDeklein,
                AlertTenal = configVer3.AlertTenal,
                AlertVenal = configVer3.AlertVenal,
                AlertFade = configVer3.AlertFade,
                AlertPureBlind = configVer3.AlertPureBlind,
                AlertTribute = configVer3.AlertTribute,
                AlertVale = configVer3.AlertVale,
                AlertProvidence = configVer3.AlertProvidence,
                AlertDelve = configVer3.AlertDelve,
                PreserveCameraDistance = configVer3.PreserveCameraDistance,
                PreserveLookAt = configVer3.PreserveLookAt,
                CameraDistance = configVer3.CameraDistance,
                LookAtX = configVer3.LookAtX,
                LookAtY = configVer3.LookAtY,
                OverrideLogPath = configVer3.OverrideLogPath,
                LogPath = configVer3.LogPath,
                PreserveSelectedSystems = configVer3.PreserveSelectedSystems,
                SelectedSystems = configVer3.SelectedSystems,
                DisplayNewFileAlerts = configVer3.DisplayNewFileAlerts,
                DisplayOpenFileAlerts = configVer3.DisplayOpenFileAlerts,
                AlertTriggers = configVer3.AlertTriggers,
                IgnoreStrings = configVer3.IgnoreStrings,
                IgnoreSystems = configVer3.IgnoreSystems,
                CharacterList = configVer3.CharacterList,
                DisplayCharacterNames = configVer3.DisplayCharacterNames,
                ShowCharacterLocations = configVer3.ShowCharacterLocations,
                CameraFollowCharacter = configVer3.CameraFollowCharacter,
                CentreOnCharacter = configVer3.CentreOnCharacter,
                MapRangeFrom = configVer3.MapRangeFrom,
                AnomalyMonitorSoundId = -1,
                AnomalyMonitorSoundPath = String.Empty
            };
            return configVer4;
        }

        private static ConfigVer5 UpgradeV4ToV5(ConfigVer4 configVer4)
        {
            ConfigVer5 configVer5 = new ConfigVer5
            {
                PreserveWindowPosition = configVer4.PreserveWindowPosition,
                PreserveWindowSize = configVer4.PreserveWindowSize,
                WindowPositionX = configVer4.WindowPositionX,
                WindowPositionY = configVer4.WindowPositionY,
                WindowSizeX = configVer4.WindowSizeX,
                WindowSizeY = configVer4.WindowSizeY,
                PreserveFullScreenStatus = configVer4.PreserveFullScreenStatus,
                IsFullScreen = configVer4.IsFullScreen,
                PreserveHomeSystem = configVer4.PreserveHomeSystem,
                HomeSystemId = configVer4.HomeSystemId,
                MonitorBranch = configVer4.MonitorBranch,
                MonitorDeklein = configVer4.MonitorDeklein,
                MonitorTenal = configVer4.MonitorTenal,
                MonitorVenal = configVer4.MonitorVenal,
                MonitorFade = configVer4.MonitorFade,
                MonitorPureBlind = configVer4.MonitorPureBlind,
                MonitorTribute = configVer4.MonitorTribute,
                MonitorVale = configVer4.MonitorVale,
                MonitorProvidence = configVer4.MonitorProvidence,
                MonitorDelve = configVer4.MonitorDelve,
                MonitorGameLog = configVer4.MonitorGameLog,
                AlertBranch = configVer4.AlertBranch,
                AlertDeklein = configVer4.AlertDeklein,
                AlertTenal = configVer4.AlertTenal,
                AlertVenal = configVer4.AlertVenal,
                AlertFade = configVer4.AlertFade,
                AlertPureBlind = configVer4.AlertPureBlind,
                AlertTribute = configVer4.AlertTribute,
                AlertVale = configVer4.AlertVale,
                AlertProvidence = configVer4.AlertProvidence,
                AlertDelve = configVer4.AlertDelve,
                PreserveCameraDistance = configVer4.PreserveCameraDistance,
                PreserveLookAt = configVer4.PreserveLookAt,
                CameraDistance = configVer4.CameraDistance,
                LookAtX = configVer4.LookAtX,
                LookAtY = configVer4.LookAtY,
                OverrideLogPath = configVer4.OverrideLogPath,
                LogPath = configVer4.LogPath,
                PreserveSelectedSystems = configVer4.PreserveSelectedSystems,
                SelectedSystems = configVer4.SelectedSystems,
                DisplayNewFileAlerts = configVer4.DisplayNewFileAlerts,
                DisplayOpenFileAlerts = configVer4.DisplayOpenFileAlerts,
                AlertTriggers = configVer4.AlertTriggers,
                IgnoreStrings = configVer4.IgnoreStrings,
                IgnoreSystems = configVer4.IgnoreSystems,
                CharacterList = configVer4.CharacterList,
                DisplayCharacterNames = configVer4.DisplayCharacterNames,
                ShowCharacterLocations = configVer4.ShowCharacterLocations,
                CameraFollowCharacter = configVer4.CameraFollowCharacter,
                CentreOnCharacter = configVer4.CentreOnCharacter,
                MapRangeFrom = configVer4.MapRangeFrom,
                AnomalyMonitorSoundId = configVer4.AnomalyMonitorSoundId,
                AnomalyMonitorSoundPath = configVer4.AnomalyMonitorSoundPath,
                ShowAlertAge = true,
                ShowAlertAgeSecs = true,
                ShowReportCount = false,
                MaxAlertAge = 15,
                MaxAlerts = 20
            };
            return configVer5;
        }

        private static ConfigVer6 UpgradeV5ToV6(ConfigVer5 configVer5)
        {
            ConfigVer6 configVer6 = new ConfigVer6
            {
                PreserveWindowPosition = configVer5.PreserveWindowPosition,
                PreserveWindowSize = configVer5.PreserveWindowSize,
                WindowPositionX = configVer5.WindowPositionX,
                WindowPositionY = configVer5.WindowPositionY,
                WindowSizeX = configVer5.WindowSizeX,
                WindowSizeY = configVer5.WindowSizeY,
                PreserveFullScreenStatus = configVer5.PreserveFullScreenStatus,
                IsFullScreen = configVer5.IsFullScreen,
                PreserveHomeSystem = configVer5.PreserveHomeSystem,
                HomeSystemId = configVer5.HomeSystemId,
                MonitorBranch = configVer5.MonitorBranch,
                MonitorDeklein = configVer5.MonitorDeklein,
                MonitorTenal = configVer5.MonitorTenal,
                MonitorVenal = configVer5.MonitorVenal,
                MonitorFade = configVer5.MonitorFade,
                MonitorPureBlind = configVer5.MonitorPureBlind,
                MonitorTribute = configVer5.MonitorTribute,
                MonitorVale = configVer5.MonitorVale,
                MonitorProvidence = configVer5.MonitorProvidence,
                MonitorDelve = configVer5.MonitorDelve,
                MonitorGameLog = configVer5.MonitorGameLog,
                AlertBranch = configVer5.AlertBranch,
                AlertDeklein = configVer5.AlertDeklein,
                AlertTenal = configVer5.AlertTenal,
                AlertVenal = configVer5.AlertVenal,
                AlertFade = configVer5.AlertFade,
                AlertPureBlind = configVer5.AlertPureBlind,
                AlertTribute = configVer5.AlertTribute,
                AlertVale = configVer5.AlertVale,
                AlertProvidence = configVer5.AlertProvidence,
                AlertDelve = configVer5.AlertDelve,
                PreserveCameraDistance = configVer5.PreserveCameraDistance,
                PreserveLookAt = configVer5.PreserveLookAt,
                CameraDistance = configVer5.CameraDistance,
                LookAtX = configVer5.LookAtX,
                LookAtY = configVer5.LookAtY,
                OverrideLogPath = configVer5.OverrideLogPath,
                LogPath = configVer5.LogPath,
                PreserveSelectedSystems = configVer5.PreserveSelectedSystems,
                SelectedSystems = configVer5.SelectedSystems,
                DisplayNewFileAlerts = configVer5.DisplayNewFileAlerts,
                DisplayOpenFileAlerts = configVer5.DisplayOpenFileAlerts,
                AlertTriggers = configVer5.AlertTriggers,
                IgnoreStrings = configVer5.IgnoreStrings,
                IgnoreSystems = configVer5.IgnoreSystems,
                CharacterList = configVer5.CharacterList,
                DisplayCharacterNames = configVer5.DisplayCharacterNames,
                ShowCharacterLocations = configVer5.ShowCharacterLocations,
                CameraFollowCharacter = configVer5.CameraFollowCharacter,
                CentreOnCharacter = configVer5.CentreOnCharacter,
                MapRangeFrom = configVer5.MapRangeFrom,
                AnomalyMonitorSoundId = configVer5.AnomalyMonitorSoundId,
                AnomalyMonitorSoundPath = configVer5.AnomalyMonitorSoundPath,
                ShowAlertAge = configVer5.ShowAlertAge,
                ShowAlertAgeSecs = configVer5.ShowAlertAgeSecs,
                ShowReportCount = configVer5.ShowReportCount,
                MaxAlertAge = configVer5.MaxAlertAge,
                MaxAlerts = configVer5.MaxAlerts,
                QueriousIntelChat = "querious",
                BranchIntelChat = "brn",
                DekleinIntelChat = "dek",
                TenalIntelChat = "tnl",
                VenalIntelChat = "vnl",
                FadeIntelChat = "fade",
                PureBlindIntelChat = "pb",
                TributeIntelChat = "tri",
                ValeIntelChat = "vale",
                ProvidenceIntelChat = "provi",
                DelveIntelChat = "delve",
                RenderWhileDragging = false
            };
            return configVer6;
        }

    }
}
